# Generated by Django 2.0.6 on 2018-06-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='GDP（亿）')),
                ('population', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='年初人口（万）')),
                ('per_gdp', models.IntegerField(blank=True, null=True, verbose_name='人均GDP（元）')),
                ('increase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='增量（亿）')),
                ('increase_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='名义增速')),
                ('year', models.IntegerField(blank=True, default=2017, null=True, verbose_name='年份')),
            ],
            options={
                'verbose_name': '地级市',
                'verbose_name_plural': '地级市GDP排名',
                'ordering': ['-amount'],
            },
        ),
    ]
