# Generated by Django 2.0.5 on 2018-05-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(blank=True, null=True, verbose_name='手机号段')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('card_type', models.CharField(max_length=50, verbose_name='手机卡类型')),
                ('region_code', models.CharField(max_length=50, verbose_name='区号')),
                ('post_code', models.IntegerField(blank=True, null=True, verbose_name='邮编')),
                ('year', models.CharField(default='2011年', max_length=50, verbose_name='资料年份')),
            ],
            options={
                'verbose_name': '手机号归属地',
                'verbose_name_plural': '手机号归属地',
                'ordering': ['-section'],
            },
        ),
    ]
