# Generated by Django 2.0.5 on 2018-05-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='city',
            new_name='region',
        ),
    ]
